# Generated by Django 3.1.6 on 2021-03-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_follow_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileUsername',
            field=models.CharField(default='k', max_length=20),
            preserve_default=False,
        ),
    ]
