# Generated by Django 3.1.6 on 2021-03-22 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0007_auto_20210322_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='startedFollowingAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
