# Generated by Django 3.1.7 on 2021-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_auto_20210328_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastLogin',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
