# Generated by Django 3.1.6 on 2021-04-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0013_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='userProfile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialmedia.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
