# Generated by Django 3.1.6 on 2021-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0016_auto_20210407_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstTime',
            field=models.BooleanField(default=False),
        ),
    ]
